paths:
  uploads: uploads
  static: ''
collections_config:
  source:
    path: ''
    icon: package_2
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  jekyll: true
timezone: America/Los_Angeles
markdown:
  engine: kramdown
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: true
    quotes: ‘’“”
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: true
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
